### ISSUE TITLE
Unable to Download MIDAS Database

### ISSUE THREAD

**Issue by yejunbin** [czbiohub/iggtools#146]
#### **Description**:
I encountered an issue while trying to download the MIDAS database using the following command:

```bash
midas database --species_list species.txt --num_cores 30 --download --midasdb_dir midasdb
```

#### **Error Message**:
```bash
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
1735046956.3:  Sleeping 2.326705168031156 seconds before retry 1 of <function download_tarball at 0x74ce01580550> with ('https://midasdb.pollard.gladstone.org/v3/uhgg/md5sum.json.tar.gz', '/Disk1/projects/ye_projects/bioinfo_workflow/midasdb'), {}.
```

#### **Cause**:
It seems that the issue arises because the MIDAS database server at `https://midasdb.pollard.gladstone.org` is currently unreachable. This is preventing the download from proceeding successfully.

#### **Steps to Reproduce**:
1. Run the following command:
   ```bash
   midas database --species_list species.txt --num_cores 30 --download --midasdb_dir midasdb
   ```
2. Observe the error message about `gzip` and `tar`.

#### **Expected Behavior**:
The MIDAS database should download and extract successfully.

#### **Additional Information**:
- The error indicates a failure to download the tarball from the server, likely due to network connectivity issues or server unavailability.
- I have verified that the server `https://midasdb.pollard.gladstone.org` is unreachable from my network.

#### **Possible Solutions**:
- It would be helpful to confirm whether the server is temporarily down or if there are network restrictions preventing access.
- An alternative download location or mirror would be useful.

**Comment by zhaoc1** [comment]
Thanks for reporting the issue. I can reproduce the database downloading error. I believe some of the servers were under maintenance during the break. I will keep an eye on this issue after the new year.

Chunyu

**Comment by zhaoc1** [comment]
Hi, 

The IT fixed the configure issue after the server shutdown and I also tested the database downloading. It should be working now. Thank you!

Chunyu

**Comment by gamalielcabria** [comment]
Hi Chunyu,

I am having the same issue as above as of today (April 1, 2025). I would just like to inform you.

Sincerely,

Gamaliel

**Comment by zhaoc1** [comment]
Hi Gamaliel,

I can't reproduce the issue on my end. Here are the commands I just tried:

```
midas database --list
midas database --init --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg
midas database --download --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg --species 100002
```

If you still have trouble downloading the database, can you share more details about the error you ran into?

Thanks.
Chunyu

**Comment by gamalielcabria** [comment]
Hi Chunyu,

The code I used just last night to download the database is this:

```
midas2 database \
--download \
--midasdb_name gtdb \
--midasdb_dir midasdb_gtdb \
--num_cores 10 \
--species all
```

It  still produce an error:
```
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file
tar: 
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: tar: stdin: unexpected end of file
Child returned status 1Child returned status 1

tar: Error is not recoverable: exiting now
tar: Error is not recoverable: exiting now
tar: Child returned status 1tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: tar: tar: Child returned status 1Child returned status 1


tar: tar: Error is not recoverable: exiting nowError is not recoverable: exiting now

tar: tar: Error is not recoverable: exiting now
Child returned status 1tar: 
Child returned status 1tar: 
Error is not recoverable: exiting now
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Child returned status 1
tar: Error is not recoverable: exiting now
1743638307.7:  Sleeping 5.514855388807542 seconds before retry 1 of <function download_tarball at 0x7
f43773fbdd0> with ('https://midasdb.pollard.gladstone.org/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/re
ferenceDatabases/midasdb/midasdb_gtdb'), {}.
1743638307.7:  Sleeping 4.251060598840874 seconds before retry 1 of <function download_tarball at 0x7
f84fada5dd0> with ('https://midasdb.pollard.gladstone.org/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/re
ferenceDatabases/midasdb/midasdb_gtdb'), {}.
1743638307.7:  Sleeping 4.566247553241409 seconds before retry 1 of <function download_tarball at 0x7
f50c5315dd0> with ('https://midasdb.pollard.gladstone.org/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/re
ferenceDatabases/midasdb/midasdb_gtdb'), {}.
1743638307.7:  Sleeping 4.513704236188527 seconds before retry 1 of <function download_tarball at 0x7
fc9a283edd0> with ('https://midasdb.pollard.gladstone.org/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/re
ferenceDatabases/midasdb/midasdb_gtdb'), {}.
```
When I run also the script you mentioned above (using midas3 i assume), the `midas database --list` works but the rest does not. Here is an error generated by `midas database --init --midasdb_name gtdb --midasdb_dir midasdb_gtdb20250403`:
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
1743699385.2:  Sleeping 2.610649296218995 seconds before retry 1 of <function download_tarball at 0x7fb9f1b3b9d0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/referenceDatabases/midasdb/midasdb_gtdb20250403'), {}.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
1743699397.9:  Sleeping 12.645964053146917 seconds before retry 2 of <function download_tarball at 0x7fb9f1b3b9d0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/work/ebg_lab/referenceDatabases/midasdb/midasdb_gtdb20250403'), {}.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/bin/midas", line 10, in <module>
    sys.exit(main())
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/__main__.py", line 25, in main
    return subcommand_main(subcommand_args)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/subcommands/database.py", line 146, in main
    init_midasdb(args)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/subcommands/database.py", line 22, in init_midasdb
    midasdb = MIDAS_DB(args.midasdb_dir, args.midasdb_name, 1)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/models/midasdb.py", line 138, in __init__
    self.md5sum = load_json(self.fetch_files("md5sum")) if self.has_md5sum else None
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/models/midasdb.py", line 190, in fetch_files
    return self.fetch_tarball(filename, list_of_species)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/models/midasdb.py", line 258, in fetch_tarball
    _fetched_file = _fetch_file_from_s3(self.construct_file_tuple(filename))
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/models/midasdb.py", line 354, in _fetch_file_from_s3
    return download_tarball(s3_path, local_dir)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/common/utils.py", line 468, in wrapped_operation
    return operation(*args, **kwargs)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/common/utils.py", line 675, in download_tarball
    command(f"set -o pipefail; wget -q -O- {ref_path} | {uncompress_cmd} {local_dir}")
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/site-packages/midas/common/utils.py", line 246, in command
    return subprocess.run(cmd, shell=shell, **subproc_args)
  File "/home/gamaliellysandergl.c/software/miniforge3/envs/midas3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'set -o pipefail; wget -q -O- https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz | tar -xz -C /work/ebg_lab/referenceDatabases/midasdb/midasdb_gtdb20250403' returned non-zero exit status 2.
```

Is this a problem on my installation?

Thanks for any help you can provide.

Cheers,

Gamaliel

**Comment by zhaoc1** [comment]
Can you install the latest version of MIDAS 3 and replace `midas2` in your command with `midas`. The rest of the command syntax don't change. Let me know how it works. Thanks.

Chunyu

**Comment by gamalielcabria** [comment]
Hi Chunyu,

Using midas 3 using the same command results to the same error.

```
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: 
gzip: stdin: unexpected end of file
stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: 
gzip: 
gzip: stdin: unexpected end of file
stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: 
gzip: 
gzip: stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: 
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: 
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file
stdin: unexpected end of file

gzip: 
gzip: 
gzip: stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file

gzip: 
gzip: 
gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file

gzip: 
gzip: 
gzip: stdin: unexpected end of file
stdin: unexpected end of file
stdin: unexpected end of file

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting nowtar: 
Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1tar: tar: 
Child returned status 1Child returned status 1tar: 

Error is not recoverable: exiting nowtar: 
tar: Error is not recoverable: exiting nowError is not recoverable: exiting now

tar: Child returned status 1tar: 
Child returned status 1tar: Error is not recoverable: exiting now

tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: tar: Child returned status 1Error is not recoverable: exiting now

tar: Error is not recoverable: exiting now
tar: tar: Child returned status 1
Child returned status 1tar: 
Error is not recoverable: exiting now
tar: Error is not recoverable: exiting nowtar: tar: 
Child returned status 1Child returned status 1

tar: Error is not recoverable: exiting nowtar: 
Error is not recoverable: exiting now
tar: tar: Child returned status 1Child returned status 1

tar: tar: Error is not recoverable: exiting nowError is not recoverable: exiting now

tar: Child returned status 1
tar: tar: Error is not recoverable: exiting nowChild returned status 1

tar: Error is not recoverable: exiting now
tar: Child returned status 1tar: tar: 
Child returned status 1Child returned status 1tar: tar: tar: tar: 

Child returned status 1tar: tar: Child returned status 1Child returned status 1Error is not recoverable: exiting nowChild returned status 1
Child returned status 1tar: tar: tar: 



tar: Error is not recoverable: exiting nowError is not recoverable: exiting now
Error is not recoverable: exiting nowChild returned status 1
tar: tar: tar: 

tar: 
Error is not recoverable: exiting nowError is not recoverable: exiting nowError is not recoverable: exiting nowtar: Error is not recoverable: exiting nowtar: 
tar: 

Child returned status 1
Error is not recoverable: exiting nowChild returned status 1


tar: Error is not recoverable: exiting nowtar: 
Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: tar: Child returned status 1Child returned status 1

tar: tar: Error is not recoverable: exiting nowError is not recoverable: exiting now

tar: Child returned status 1tar: 
tar: Child returned status 1Error is not recoverable: exiting now

tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: Child returned status 1
tar: Error is not recoverable: exiting now
1743976521.8:  Sleeping 3.396952371208309 seconds before retry 1 of <function download_tarball at 0x7f8d56a08ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.5797335676370015 seconds before retry 1 of <function download_tarball at 0x7f88967d7ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.9153775311141645 seconds before retry 1 of <function download_tarball at 0x7facce847ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.134310591330767 seconds before retry 1 of <function download_tarball at 0x7f1e25dddca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.8027800281099 seconds before retry 1 of <function download_tarball at 0x7fd1d77bfca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.5369473779931258 seconds before retry 1 of <function download_tarball at 0x7fbe7e2f9ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.826395884573866 seconds before retry 1 of <function download_tarball at 0x7f01d18a0ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.571172776872798 seconds before retry 1 of <function download_tarball at 0x7f81a34f2ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.3147790295710746 seconds before retry 1 of <function download_tarball at 0x7fa7e3c8cca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.01084483178278 seconds before retry 1 of <function download_tarball at 0x7f77828deca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.478021178812884 seconds before retry 1 of <function download_tarball at 0x7f90a5352ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.550565995358771 seconds before retry 1 of <function download_tarball at 0x7f855f3a0ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.226289820013168 seconds before retry 1 of <function download_tarball at 0x7fc76088dca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.7823655454377207 seconds before retry 1 of <function download_tarball at 0x7f529f7b1ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.0510903667688303 seconds before retry 1 of <function download_tarball at 0x7f3fb88eeca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.602453883698796 seconds before retry 1 of <function download_tarball at 0x7fa61e8b4ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.2193614780398794 seconds before retry 1 of <function download_tarball at 0x7fe01f85aca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.756458870473465 seconds before retry 1 of <function download_tarball at 0x7febaca0eca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.620402088336217 seconds before retry 1 of <function download_tarball at 0x7f87fbea8ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.0989420381670088 seconds before retry 1 of <function download_tarball at 0x7f9e9c0a0ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.3249396177185813 seconds before retry 1 of <function download_tarball at 0x7f454592eca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.426724168180246 seconds before retry 1 of <function download_tarball at 0x7fa30aec0ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.843361810530938 seconds before retry 1 of <function download_tarball at 0x7fee9744aca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.4727536942535715 seconds before retry 1 of <function download_tarball at 0x7f5b8e1d3ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.8893689949922154 seconds before retry 1 of <function download_tarball at 0x7fe4f6621ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.024021767317027 seconds before retry 1 of <function download_tarball at 0x7f48820fdca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.9680003396691856 seconds before retry 1 of <function download_tarball at 0x7fdeade1cca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.288130391038667 seconds before retry 1 of <function download_tarball at 0x7f5b2e65dca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.362191569992022 seconds before retry 1 of <function download_tarball at 0x7f6197476ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.228034391611831 seconds before retry 1 of <function download_tarball at 0x7fc7a55f6ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.4738671668587884 seconds before retry 1 of <function download_tarball at 0x7f928cf08ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.1877157353535144 seconds before retry 1 of <function download_tarball at 0x7f9a1bf06ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.21996512967049 seconds before retry 1 of <function download_tarball at 0x7f63c86f2ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.119597790481503 seconds before retry 1 of <function download_tarball at 0x7ff04ae56ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 5.552841079396806 seconds before retry 1 of <function download_tarball at 0x7f9ea4a8eca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.1389666542304226 seconds before retry 1 of <function download_tarball at 0x7f36f372dca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.298560332413006 seconds before retry 1 of <function download_tarball at 0x7fde63862ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 3.1630061640403877 seconds before retry 1 of <function download_tarball at 0x7fc12c801ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 4.01149068398942 seconds before retry 1 of <function download_tarball at 0x7f0a4c9d6ca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
1743976521.8:  Sleeping 2.10785937506382 seconds before retry 1 of <function download_tarball at 0x7f1d328fbca0> with ('https://midasdb.pollard.gladstone.org/v3/gtdb/md5sum.json.tar.gz', '/path/to/midasdb/midas2_gtdb'), {}.
```


Cheers,

Gamaliel
